[target.'cfg(any(target_arch = "riscv32", target_arch = "xtensa"))']
# runner = "probe-rs run --chip esp32"
runner = "espflash flash --monitor"


[env]
ESP_LOG="INFO"

[build]
rustflags = [
  "-C", "link-arg=-nostartfiles",
]

target = "xtensa-esp32-none-elf"

[unstable]
build-std = ["core"]
